### ISSUE TITLE
3.2不兼容啊

### ISSUE THREAD

**Issue by wangzhipeng-vicky** [octologs/flutter_picker_plus#5]
The getter 'headline6' isn't defined for the class 'TextTheme'.

**Comment by Ben1980** [comment]
Since Flutter 3.19 `headline6` is deprecated and is now not available anymore, see [TextTheme](https://api.flutter.dev/flutter/material/TextTheme-class.html). See also [flutter.dev/go/deprecations-removed-after-3-19](flutter.dev/go/deprecations-removed-after-3-19).
With 3054113c6fe9a25766d54ea12673c25ccc7da9aa all `headline6` has been exchanged with `titleLarge`.

**Comment by Ben1980** [comment]
@wangzhipeng-vicky, do you have more information? Otherwise I will close the issue if that's ok.

**Comment by wangzhipeng-vicky** [comment]
国际化能给支持一下印尼语吗

**Comment by Ben1980** [comment]
I don't speak Chinese but what I roughly got from google translate is that you would like to have Indonesian language support, right?
If so, that's not a big deal, I can add it.

**Comment by wangzhipeng-vicky** [comment]
> @wangzhipeng-vicky I don't speak Chinese but what I roughly got from google translate is that you would like to have Indonesian language support, right? If so, that's not a big deal, I can add it.

Yes, I need Indonesian, please add it
