### ISSUE TITLE
How to dynamic the language

### ISSUE THREAD

**Issue by wangzhipeng-vicky** [octologs/flutter_picker_plus#7]
I changed the language in the app using easy_localization instead of following the phone's language. In this case, how do I set up to change the language in flutter_picker_plus

**Comment by Ben1980** [comment]
Hi @wangzhipeng-vicky, Sorry for the late response, GitHub wasn't giving me a notification 😒 I don't know about easy_localization but if it is utilizing flutters l10n mechanism, using the right ISO code, and the language you are using is supported by flutter_picker_plus it will work. Otherwise, it will show you English as a fallback. At the end, flutter_picker_plus is just calling `PickerLocalizations.of(context).text`. Do you have any examples I could try out?

**Comment by Ben1980** [comment]
@wangzhipeng-vicky any Feedback? I will close this issue soon.

**Comment by wangzhipeng-vicky** [comment]
> Hi @wangzhipeng-vicky, Sorry for the late response, GitHub wasn't giving me a notification 😒 I don't know about easy_localization but if it is utilizing flutters l10n mechanism, using the right ISO code, and the language you are using is supported by flutter_picker_plus it will work. Otherwise, it will show you English as a fallback. At the end, flutter_picker_plus is just calling `PickerLocalizations.of(context).text`. Do you have any examples I could try out?
![20241009-171611](https://github.com/user-attachments/assets/03e81539-8605-4cb0-b148-3eb34d432284)

I'm sorry. I've been so busy lately that I forgot about it. Here's the thing.

I changed the language from Chinese to English in the app. When I open the relevant page of this component again, I need this component to be changed into English, please see the following picture. So what do I need to do with this component. I now understand that the components are automatically set according to the system language.

**Comment by Ben1980** [comment]
As I mentioned it is using the context and therefore automatically switching. I would need an example code to know exactly what you trying here and reproduce it.
By the way? What's the problem with sticking to the system language and doing it manually?
